-- Social graph + reactions/comments/feed. Tables + RLS only.
-- See docs/BACKEND_ARCHITECTURE.md §4.6.

create table public.follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  followee_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, followee_id),
  check (follower_id <> followee_id)
);

create table public.reactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  target_type text not null check (target_type in ('feed_item', 'comment')),
  target_id uuid not null,
  reaction_id text not null check (reaction_id in ('thich', 'cuoi', 'dinh', 'bat-ngo', 'vo-tri')),
  created_at timestamptz not null default now(),
  unique (user_id, target_type, target_id)
);

create table public.comments (
  id uuid primary key default gen_random_uuid(),
  target_type text not null check (target_type in ('activity', 'feed_item')),
  target_id text not null,
  author_id uuid not null references public.profiles(id) on delete cascade,
  parent_comment_id uuid references public.comments(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index comments_target_created_idx on public.comments (target_type, target_id, created_at desc);

create table public.feed_items (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (event_type in ('level_up', 'milestone', 'achievement', 'quest_claim')),
  text text not null,
  created_at timestamptz not null default now()
);
create index feed_items_created_idx on public.feed_items (created_at desc);

alter table public.follows enable row level security;
alter table public.reactions enable row level security;
alter table public.comments enable row level security;
alter table public.feed_items enable row level security;

create policy "follows are publicly readable" on public.follows for select using (true);
create policy "users can create their own follows"
  on public.follows for insert with check (auth.uid() = follower_id);
create policy "users can remove their own follows"
  on public.follows for delete using (auth.uid() = follower_id);

create policy "reactions are publicly readable" on public.reactions for select using (true);
create policy "users can react as themselves"
  on public.reactions for insert with check (auth.uid() = user_id);
create policy "users can change their own reaction"
  on public.reactions for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users can remove their own reaction"
  on public.reactions for delete using (auth.uid() = user_id);

create policy "comments are publicly readable" on public.comments for select using (deleted_at is null);
create policy "users can post comments as themselves"
  on public.comments for insert with check (auth.uid() = author_id);
create policy "users can soft-delete their own comments"
  on public.comments for update using (auth.uid() = author_id) with check (auth.uid() = author_id);

-- feed_items: public read, no client write policy at all — every row is
-- system-generated by the security-definer functions in
-- 20260724000012_functions.sql after a real notable event (level up,
-- milestone, achievement, quest claim), never user-authored free text.
create policy "feed_items are publicly readable" on public.feed_items for select using (true);
